In [5]:
import numpy as np

In [8]:
np.c_?

Type:        CClass
String form: <numpy.lib.index_tricks.CClass object at 0x0000026C2BB85EE0>
Length:      0
File:        c:\users\anton\.virtualenvs\01_python_packages-0oszqxsv\lib\site-packages\numpy\lib\index_tricks.py
Docstring:  
Translates slice objects to concatenation along the second axis.

This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
useful because of its common occurrence. In particular, arrays will be
stacked along their last axis after being upgraded to at least 2-D with
1's post-pended to the shape (column vectors made out of 1-D arrays).

See Also
--------
column_stack : Stack 1-D arrays as columns into a 2-D array.
r_ : For more detailed documentation.

Examples
--------
>>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
array([[1, 2, 3, ..., 4, 5, 6]])


In [13]:
x = np.arange(0, 5)
y = x + 1
x, y

(array([0, 1, 2, 3, 4]), array([1, 2, 3, 4, 5]))

In [15]:
zip_list = list(zip(x, y))
zip_list

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5)]

In [20]:
c_list = np.c_[x, y]
c_list

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 2 has size 1

array([[0, 1, 2, 3, 4, 0, 0, 1, 2, 3, 4, 5]])