In [1]:
import numpy as np

In [23]:
a = np.zeros((4, 5))
np.fill_diagonal(a, 1)

In [24]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [25]:
a[[0, 1]]

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [26]:
b = a[[0, 1]]

In [27]:
b.shape

(2, 5)

In [30]:
a[[0, 1],[1, 3]]

array([0., 0.])