In [3]:
import numpy as np

In [4]:
x = np.array([1, 2, 3, 4, 5, 4, 3, 2, 5, 0])

In [5]:
x_5 = (x == 5)

In [6]:
x_5

array([False, False, False, False,  True, False, False, False,  True,
       False])

In [11]:
x_5.astype(int)
x_5

array([False, False, False, False,  True, False, False, False,  True,
       False])

In [13]:
x_5  = x_5.astype(int)
x_5

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0])