TEST

In [149]:
import numpy as np

x = [i for i in range(10)]

y = np.array(x)
print(type(y))
print(y)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [143]:
try:
    print(y[2][3])
except Exception as ex:
    print(type(ex).__name__, ex.args)

IndexError ('invalid index to scalar variable.',)


In [144]:
try:
    print(y[2, 3])
except Exception as ex:
    print(type(ex).__name__, ex.args)

IndexError ('too many indices for array: array is 1-dimensional, but 2 were indexed',)


In [145]:
# Syntax error
# try:
#     print(y[2 3])
# except Exception as ex:
#     print(type(ex).__name__, ex.args)

In [146]:
try:
    print(y['2, 3'])
except Exception as ex:
    print(type(ex).__name__, ex.args)

IndexError ('only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices',)


In [150]:
try:
    print(y[2:3])
except Exception as ex:
    print(type(ex).__name__, ex.args)

[2]


In [151]:
try:
    print(y[[2, 4]])
except Exception as ex:
    print(type(ex).__name__, ex.args)

[2 4]


In [161]:
matrix_x = [[i + j * 5 for i in range (1, 6)] for j in range(0, 5)]
matrix_x

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]]

In [162]:
try:
    print(matrix_x[0, 1])
except Exception as ex:
    print(type(ex).__name__, ex.args)

TypeError ('list indices must be integers or slices, not tuple',)


In [163]:
print(matrix_x[0][1])

2


In [164]:
matrix_x = [[i + j * 5 for i in range (1, 6)] for j in range(0, 5)]
matrix_y = np.array(matrix_x)
print(matrix_y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [165]:
matrix_y[0, 0]

1

In [166]:
matrix_y[0][1]

2

In [104]:
simport pandas as pd

dic_ = {'col1': [1, 2, None, 4, 5], 'col2': ['one', 'two', 'three', None, None]}
frame = pd.DataFrame(dic_)

In [105]:
frame.info()
frame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    4 non-null      float64
 1   col2    3 non-null      object 
dtypes: float64(1), object(1)
memory usage: 208.0+ bytes


col1   col2
0   1.0    one
1   2.0    two
2   NaN  three
3   4.0   None
4   5.0   None

In [106]:
frame.fillna('', inplace=True)
frame

col1   col2
0  1.0    one
1  2.0    two
2       three
3  4.0       
4  5.0

In [107]:
print(frame.loc[2, 'col1'])
print(type(frame.loc[2, 'col1']))


<class 'str'>


In [108]:
print(frame.loc[3, 'col2'])
print(type(frame.loc[3, 'col2']))


<class 'str'>


In [109]:
frame.info

<bound method DataFrame.info of   col1   col2
0  1.0    one
1  2.0    two
2       three
3  4.0       
4  5.0       >

In [110]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    5 non-null      object
 1   col2    5 non-null      object
dtypes: object(2)
memory usage: 208.0+ bytes
