In [2]:
import numpy as np
from numpy.linalg import norm

In [4]:
a = np.array([-1, 2, -1])
norm_a = norm(a, ord=1)
print(norm_a)

4.0


In [8]:

a = np.array([1, 2, 3])
b = np.array([-3, 1, 1])

print(np.dot(a, b))

2


In [11]:
f = np.arange(1, 2, 0.3, dtype=float)
print(f)

[1.  1.3 1.6 1.9]


In [12]:
c = np.array([False, False, True])
print(c)

[False False  True]


In [15]:
b = np.array(1, 2, 3, 4, 5, dtype=float)
print(b)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [19]:
b = np.array([1, 2, 3, 4, 5], dtype=float)
print(b)

[1. 2. 3. 4. 5.]


In [66]:
from scipy.spatial.distance import cdist

a = np.array([6, 3, -5])
b = np.array([-1, 0, 7])
    #%%
a.shape

In [68]:
# cdist(b, a, metric='euclidean')

In [69]:
cdist(a[np.newaxis, :], b[np.newaxis, :], metric='euclidean')

array([[14.2126704]])

In [70]:
a[np.newaxis, :]

array([[ 6,  3, -5]])

In [71]:
b[np.newaxis, :]

array([[-1,  0,  7]])

In [72]:
a[np.newaxis, :].shape

(1, 3)

In [73]:
cdist(a[:, np.newaxis], b[:, np.newaxis], metric='euclidean')

array([[ 7.,  6.,  1.],
       [ 4.,  3.,  4.],
       [ 4.,  5., 12.]])

In [74]:
a[:, np.newaxis]

array([[ 6],
       [ 3],
       [-5]])

In [30]:
b   [:, np.newaxis]

array([[-1],
       [ 0],
       [ 7]])

In [37]:
a[:, np.newaxis].shape

(3, 1)

In [ ]:
type(a[:, np.newaxis])

In [ ]:
type(a.reshape(3, 1))

In [42]:
norm(a, ord=2) - norm(b, ord=2)

1.2955324534752801

In [45]:
a = np.array([0, -1, 11])
b = np.array([3, 7, 2])



In [46]:
a * b

array([ 0, -7, 22])

In [47]:
a.dot(b)


15

In [48]:
np.dot(a, b)


15

In [49]:
a = np.array([1, 2, 3])

In [52]:
a[np.newaxis, :]


array([[1, 2, 3]])

In [54]:
a[:, np.newaxis]


array([[1],
       [2],
       [3]])