In [3]:
import numpy as np

2. Найти ранг матрицы

In [4]:
a2 = np.array([[1, 1, 2], [0, 1, 2]])
np.linalg.matrix_rank(a2)

2

4. Определить тип матрицы

In [21]:
a4 = np.array([[1, 1], [1, 2]])
a4_T = a4.T
a4 * a4_T



array([[1, 1],
       [1, 4]])

In [24]:
print(a4_T * a4)
print("Произведение исходной и транспонированнной не равно единичной матрице")

[[1 1]
 [1 4]]
Произведение исходной и транспонированнной не равно единичной матрице


Какие из нижеприведенных команд корректно отработают и создадут двумерный массив?

In [39]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [40]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.eye((4, 5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [42]:
np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [43]:
np.arange(1, 13, 2).reshape((3, 2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

Пусть создан массив с помощью команды a = np.eye(4, 5). Что вернет операция a[[0, 3], [1, 3]]?


In [69]:
a = np.eye(4,5)
print(a)
a1 = a[[0, 3], [1, 3]]
print(a1)
print(type(a1))
print(a1.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[0. 1.]
<class 'numpy.ndarray'>
(2,)
