https://github.com/takenory/10-minutes-to-pandas

http://pandas.pydata.org/pandas-docs/stable/10min.html

# 10 Minutes to pandas

This is a short introduction to pandas, geared mainly for new users. You can see more complex recipes in the [Cookbook](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook) 

Customarily, we import as follows:

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
%matplotlib inline

## Object Creation

See the [Data Structure Intro section](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dsintro) 

Creating a Series by passing a list of values, letting pandas create a default integer index:

In [3]:
s = pd.Series([1,3,5,np.nan,6,8])

In [4]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a DataFrame by passing a numpy array, with a datetime index and labeled columns:

In [5]:
dates = pd.date_range('20130101', periods=6)

In [6]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
# test numpy.ndarray
array_01 = np.random.randn(6,4)
print(type(array_01))

for i in array_01:
    for j in i:
        print(i, j)

<class 'numpy.ndarray'>
[-0.37177515 -0.45340642  1.29793279 -0.06605353] -0.3717751516033183
[-0.37177515 -0.45340642  1.29793279 -0.06605353] -0.45340641627855055
[-0.37177515 -0.45340642  1.29793279 -0.06605353] 1.2979327884452105
[-0.37177515 -0.45340642  1.29793279 -0.06605353] -0.06605352759940239
[-1.3674023   0.30010003 -0.26799322 -0.38570292] -1.3674022964167782
[-1.3674023   0.30010003 -0.26799322 -0.38570292] 0.30010003362056137
[-1.3674023   0.30010003 -0.26799322 -0.38570292] -0.2679932165564312
[-1.3674023   0.30010003 -0.26799322 -0.38570292] -0.38570291997834477
[-1.63084462 -0.70695442  1.66033455 -0.32921668] -1.630844624552014
[-1.63084462 -0.70695442  1.66033455 -0.32921668] -0.7069544248337956
[-1.63084462 -0.70695442  1.66033455 -0.32921668] 1.660334546640667
[-1.63084462 -0.70695442  1.66033455 -0.32921668] -0.329216675309008
[-0.68844492  0.17685378 -0.39282386  0.138754  ] -0.6884449172924437
[-0.68844492  0.17685378 -0.39282386  0.138754  ] 0.1768537849823562

In [8]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

In [9]:
df

A         B         C         D
2013-01-01 -0.379865  0.708623  2.009224  2.058501
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993
2013-01-05 -0.035739 -0.729738  0.642678  0.144706
2013-01-06  0.355690  1.278878  1.555016  0.020501

Creating a DataFrame by passing a dict of objects that can be converted to series-like.

In [10]:
df2 = pd.DataFrame({'A':1.,
                   'B':pd.Timestamp('20130102'),
                   'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                   'D':np.array([3]*4,dtype='int32'),
                   'E':pd.Categorical(["test","train","test","train"]),
                   'F':'foo'})

In [11]:
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Having specific [dtypes](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-dtypes)

In [12]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

If you’re using IPython, tab completion for column names (as well as public attributes) is automatically enabled. Here’s a subset of the attributes that will be completed:

In [13]:
# df2.<TAB>

As you can see, the columns A, B, C, and D are automatically tab completed. E is there as well; the rest of the attributes have been truncated for brevity.

## Viewing Data

See the [Basics section](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics) 

See the top & bottom rows of the frame

In [14]:
df.head()

A         B         C         D
2013-01-01 -0.379865  0.708623  2.009224  2.058501
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993
2013-01-05 -0.035739 -0.729738  0.642678  0.144706

In [15]:
df.tail(3) # Показывает данные с хвоста data_frame

A         B         C         D
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993
2013-01-05 -0.035739 -0.729738  0.642678  0.144706
2013-01-06  0.355690  1.278878  1.555016  0.020501

Display the index, columns, and the underlying numpy data

In [16]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [17]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [18]:
df.to_numpy()

array([[-0.37986498,  0.70862314,  2.00922428,  2.05850141],
       [-0.34523685,  0.10616197, -1.72824438, -0.37940741],
       [-2.70146674, -1.25815899, -0.37496655, -0.48383773],
       [ 0.86478226, -0.04236525, -0.22331504, -1.82199314],
       [-0.03573851, -0.72973766,  0.64267799,  0.14470646],
       [ 0.35569016,  1.2788783 ,  1.55501626,  0.02050135]])

In [19]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [20]:
df.values

# Warning
# We recommend using DataFrame.to_numpy() instead.
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html

array([[-0.37986498,  0.70862314,  2.00922428,  2.05850141],
       [-0.34523685,  0.10616197, -1.72824438, -0.37940741],
       [-2.70146674, -1.25815899, -0.37496655, -0.48383773],
       [ 0.86478226, -0.04236525, -0.22331504, -1.82199314],
       [-0.03573851, -0.72973766,  0.64267799,  0.14470646],
       [ 0.35569016,  1.2788783 ,  1.55501626,  0.02050135]])

In [21]:
df2.values

# Warning
# We recommend using DataFrame.to_numpy() instead.
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.values.html


array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

Describe shows a quick statistic summary of your data

In [22]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.373639  0.010567  0.313399 -0.076922
std    1.232835  0.923640  1.375215  1.258650
min   -2.701467 -1.258159 -1.728244 -1.821993
25%   -0.371208 -0.557895 -0.337054 -0.457730
50%   -0.190488  0.031898  0.209681 -0.179453
75%    0.257833  0.558008  1.326932  0.113655
max    0.864782  1.278878  2.009224  2.058501

Transposing your data

In [23]:
df.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.379865   -0.345237   -2.701467    0.864782   -0.035739    0.355690
B    0.708623    0.106162   -1.258159   -0.042365   -0.729738    1.278878
C    2.009224   -1.728244   -0.374967   -0.223315    0.642678    1.555016
D    2.058501   -0.379407   -0.483838   -1.821993    0.144706    0.020501

Sorting by an axis

In [28]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01  2.058501  2.009224  0.708623 -0.379865
2013-01-02 -0.379407 -1.728244  0.106162 -0.345237
2013-01-03 -0.483838 -0.374967 -1.258159 -2.701467
2013-01-04 -1.821993 -0.223315 -0.042365  0.864782
2013-01-05  0.144706  0.642678 -0.729738 -0.035739
2013-01-06  0.020501  1.555016  1.278878  0.355690

Sorting by value

In [32]:
df.sort_values(by='B')
# df.sort_values(by='B', ascending=False)

A         B         C         D
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838
2013-01-05 -0.035739 -0.729738  0.642678  0.144706
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407
2013-01-01 -0.379865  0.708623  2.009224  2.058501
2013-01-06  0.355690  1.278878  1.555016  0.020501

## Selection

**Note:** While standard Python / Numpy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, .at, .iat, .loc, .iloc and .ix.

See the indexing documentation [Indexing and Selecting Data](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing) and [MultiIndex / Advanced Indexing](http://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced)

### Getting

Selecting a single column, which yields a Series, equivalent to df.A

In [34]:
print(type(df['A']))
df['A']

<class 'pandas.core.series.Series'>


2013-01-01   -0.379865
2013-01-02   -0.345237
2013-01-03   -2.701467
2013-01-04    0.864782
2013-01-05   -0.035739
2013-01-06    0.355690
Freq: D, Name: A, dtype: float64

Selecting via [], which slices the rows.

In [35]:
print(type(df[0:3]))
df[0:3]

<class 'pandas.core.frame.DataFrame'>


A         B         C         D
2013-01-01 -0.379865  0.708623  2.009224  2.058501
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838

In [37]:
print(type(df['20130102':'20130104']))
df['20130102':'20130104']

<class 'pandas.core.frame.DataFrame'>


A         B         C         D
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993

### Selection by Label

See more in [Selection by Label](Selection by Label)

For getting a cross section using a label

In [41]:
print(type(df.loc[dates[0]]))
df.loc[dates[0]]

<class 'pandas.core.series.Series'>


A   -0.379865
B    0.708623
C    2.009224
D    2.058501
Name: 2013-01-01 00:00:00, dtype: float64

Selection by Label

In [44]:
print(type(df.loc[:,['A','B']]))
df.loc[:,['A','B']]

<class 'pandas.core.frame.DataFrame'>


A         B
2013-01-01 -0.379865  0.708623
2013-01-02 -0.345237  0.106162
2013-01-03 -2.701467 -1.258159
2013-01-04  0.864782 -0.042365
2013-01-05 -0.035739 -0.729738
2013-01-06  0.355690  1.278878

Showing label slicing, both endpoints are included

In [47]:
print(type(df.loc['20130102':'20130104',['A','B']]))
df.loc['20130102':'20130104',['A','B']]

<class 'pandas.core.frame.DataFrame'>


A         B
2013-01-02 -0.345237  0.106162
2013-01-03 -2.701467 -1.258159
2013-01-04  0.864782 -0.042365

Reduction in the dimensions of the returned object

In [52]:
print(type(df.loc['20130102',['A','B']]))
df.loc['20130102',['A','B']]

<class 'pandas.core.series.Series'>


A   -0.345237
B    0.106162
Name: 2013-01-02 00:00:00, dtype: float64

For getting a scalar value

In [53]:
print(type(df.loc[dates[0],'A']))
df.loc[dates[0],'A']

<class 'numpy.float64'>


-0.3798649771699446

### Selection by Position

See more in [Selection by Position](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-integer)

Select via the position of the passed integers

In [58]:
print(type(df.iloc[3])) 
df.iloc[3] # выбирается строка с индексом = 3

<class 'pandas.core.series.Series'>


A    0.864782
B   -0.042365
C   -0.223315
D   -1.821993
Name: 2013-01-04 00:00:00, dtype: float64

By integer slices, acting similar to numpy/python

In [65]:
df.iloc[3:5,0:2] # выбираеются элементы с по первой оси с индексами от 3 до 4 (последний элемент среза не учитывается) по втророй оси от 0 до 1 (последний элемент среза не учитывается).

A         B
2013-01-04  0.864782 -0.042365
2013-01-05 -0.035739 -0.729738

By lists of integer position locations, similar to the numpy/python style

In [67]:
df.iloc[[1,2,4],[0,2]]

A         C
2013-01-02 -0.345237 -1.728244
2013-01-03 -2.701467 -0.374967
2013-01-05 -0.035739  0.642678

For slicing rows explicitly

In [68]:
df.iloc[1:3,:]

A         B         C         D
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838

For slicing columns explicitly

In [69]:
df.iloc[:,1:3]

B         C
2013-01-01  0.708623  2.009224
2013-01-02  0.106162 -1.728244
2013-01-03 -1.258159 -0.374967
2013-01-04 -0.042365 -0.223315
2013-01-05 -0.729738  0.642678
2013-01-06  1.278878  1.555016

For getting a value explicitly

In [70]:
df.iloc[1,1]

0.1061619731761601

For getting fast access to a scalar (equiv to the prior method)

In [71]:
df.iat[1,1]

0.1061619731761601

## Boolean Indexing

Using a single column’s values to select data.

In [72]:
df[df.A > 0]

A         B         C         D
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993
2013-01-06  0.355690  1.278878  1.555016  0.020501

A where operation for getting.

In [77]:
df

A         B         C         D
2013-01-01 -0.379865  0.708623  2.009224  2.058501
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993
2013-01-05 -0.035739 -0.729738  0.642678  0.144706
2013-01-06  0.355690  1.278878  1.555016  0.020501

In [79]:
filter = df > 0
df[filter] # Возвращается новый DataFrame, в котором значения не соответствующией услвию заменяются на NaN

A         B         C         D
2013-01-01       NaN  0.708623  2.009224  2.058501
2013-01-02       NaN  0.106162       NaN       NaN
2013-01-03       NaN       NaN       NaN       NaN
2013-01-04  0.864782       NaN       NaN       NaN
2013-01-05       NaN       NaN  0.642678  0.144706
2013-01-06  0.355690  1.278878  1.555016  0.020501

In [80]:
df[df > 0]

A         B         C         D
2013-01-01       NaN  0.708623  2.009224  2.058501
2013-01-02       NaN  0.106162       NaN       NaN
2013-01-03       NaN       NaN       NaN       NaN
2013-01-04  0.864782       NaN       NaN       NaN
2013-01-05       NaN       NaN  0.642678  0.144706
2013-01-06  0.355690  1.278878  1.555016  0.020501

Using the isin() method for filtering:

In [81]:
df2 = df.copy()

In [93]:
df2['E'] = ['one','one', 'two','three','four','three']
# df2['E'] = ['one','one', 'two','three','four']
# ValueError: Length of values does not match length of index

In [94]:
df2

A         B         C         D      E
2013-01-01 -0.379865  0.708623  2.009224  2.058501    one
2013-01-02 -0.345237  0.106162 -1.728244 -0.379407    one
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838    two
2013-01-04  0.864782 -0.042365 -0.223315 -1.821993  three
2013-01-05 -0.035739 -0.729738  0.642678  0.144706   four
2013-01-06  0.355690  1.278878  1.555016  0.020501  three

In [95]:
df2[df2['E'].isin(['two','four'])]

A         B         C         D     E
2013-01-03 -2.701467 -1.258159 -0.374967 -0.483838   two
2013-01-05 -0.035739 -0.729738  0.642678  0.144706  four

## Setting

Setting a new column automatically aligns the data by the indexes

In [96]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102',periods=6))

In [97]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [ ]:
df['F'] = s1

Setting values by label

In [ ]:
df.at[dates[0],'A'] = 0

Settomg values by position

In [ ]:
df.iat[0,1] = 0

Setting by assigning with a numpy array

In [ ]:
df.loc[:,'D'] = np.array([5] * len(df))

The result of the prior setting operations

In [ ]:
df

A where operation with setting.

In [ ]:
df2 = df.copy()

In [ ]:
df2[df2 > 0] = -df2

In [ ]:
df2

## Missing Data

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations. See the Missing Data section

Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data.

In [ ]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])

In [ ]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [ ]:
df1

To drop any rows that have missing data.

In [ ]:
df1.dropna(how='any')

Filling missing data

In [ ]:
df1.fillna(value=5)

To get the boolean mask where values are nan

In [ ]:
pd.isnull(df1)

## Operations

See the [Basic section on Binary Ops](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-binop)

### Stats

Operations in general exclude missing data.

Performing a descriptive statistic

In [ ]:
df.mean()

Same operation on the other axis

In [ ]:
df.mean(1)

Operating with objects that have different dimensionality and need alignment. In addition, pandas automatically broadcasts along the specified dimension.

In [ ]:
s = pd.Series([1,3,5,np.nan,6,8], index=dates).shift(2)

In [ ]:
s

In [ ]:
df.sub(s, axis='index')

### Apply

Applying functions to the data

In [ ]:
df.apply(np.cumsum)

In [ ]:
df.apply(lambda x: x.max() - x.min())

### Histogramming

See more at [Histogramming and Discretization](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-discretization)

In [ ]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [ ]:
s

In [ ]:
s.value_counts()

### String Methods

Series is equipped with a set of string processing methods in the str attribute that make it easy to operate on each element of the array, as in the code snippet below. Note that pattern-matching in str generally uses [regular expressions](https://docs.python.org/2/library/re.html) by default (and in some cases always uses them). See more at [Vectorized String Methods](http://pandas.pydata.org/pandas-docs/stable/text.html#text-string-methods).

In [ ]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])

In [ ]:
s.str.lower()

## Merge

### Concat

pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

See the [Merging section](http://pandas.pydata.org/pandas-docs/stable/merging.html#merging)

Concatenating pandas objects together with concat():

In [ ]:
df = pd.DataFrame(np.random.randn(10, 4))

In [ ]:
df

In [ ]:
# break it into pieces
pieces = [df[:3], df[3:7], df[7:]]

In [ ]:
pd.concat(pieces)

### Join

SQL style merges. See the [Database style joining](http://pandas.pydata.org/pandas-docs/stable/merging.html#merging-join)

In [ ]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})

In [ ]:
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

In [ ]:
left

In [ ]:
right

In [ ]:
pd.merge(left, right, on='key')

### Append

Append rows to a dataframe. See the [Appending](http://pandas.pydata.org/pandas-docs/stable/merging.html#merging-concatenation)

In [ ]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])

In [ ]:
df

In [ ]:
s = df.iloc[3]

In [ ]:
df.append(s, ignore_index=True)

## Grouping

By “group by” we are referring to a process involving one or more of the following steps

* **Splitting** the data into groups based on some criteria
* **Applying** a function to each group independently
* **Combining** the results into a data structure

See the [Grouping section](http://pandas.pydata.org/pandas-docs/stable/groupby.html#groupby)

In [ ]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                                    'B' : ['one', 'one', 'two', 'three','two', 'two', 'one', 'three'],
                                    'C' : np.random.randn(8),
                                     'D' : np.random.randn(8)})

In [ ]:
df

Grouping and then applying a function sum to the resulting groups.

In [ ]:
df.groupby('A').sum()

In [ ]:
df.groupby(['A','B']).sum()

## Reshaping

See the sections on [Hierarchical Indexing](http://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced-hierarchical) and [Reshaping](http://pandas.pydata.org/pandas-docs/stable/reshaping.html#reshaping-stacking).

### Stack

In [ ]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
                                ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]))

In [ ]:
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])

In [ ]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])

In [ ]:
df2 = df[:4]

In [ ]:
df2

The stack() method “compresses” a level in the DataFrame’s columns.

In [ ]:
stacked = df2.stack()

In [ ]:
stacked

With a “stacked” DataFrame or Series (having a MultiIndex as the index), the inverse operation of stack() is unstack(), which by default unstacks the **last level**:

In [ ]:
stacked.unstack()

In [ ]:
stacked.unstack(1)

In [ ]:
stacked.unstack(0)

### Pivot Tables

See the section on [Pivot Tables](http://pandas.pydata.org/pandas-docs/stable/reshaping.html#reshaping-pivot).

In [ ]:
df = pd.DataFrame({'A' : ['one', 'one', 'two', 'three'] * 3,
                                    'B' : ['A', 'B', 'C'] * 4,
                                    'C' : ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 2,
                                    'D' : np.random.randn(12),
                                    'E' : np.random.randn(12)})

In [ ]:
df

We can produce pivot tables from this data very easily:

In [ ]:
pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])

## Time Series

pandas has simple, powerful, and efficient functionality for performing resampling operations during frequency conversion (e.g., converting secondly data into 5-minutely data). This is extremely common in, but not limited to, financial applications. See the [Time Series section](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#timeseries)

In [ ]:
rng = pd.date_range('1/1/2012', periods=100, freq='S')

In [ ]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts.resample('5Min').sum()

Time zone representation

In [ ]:
rng = pd.date_range('3/6/2012 00:00', periods=5, freq='D')

In [ ]:
ts = pd.Series(np.random.randn(len(rng)), rng)

In [ ]:
ts

In [ ]:
ts_utc = ts.tz_localize('UTC')

In [ ]:
ts_utc


Convert to another time zone

In [ ]:
ts_utc.tz_convert('US/Eastern')


Converting between time span representations

In [ ]:
rng = pd.date_range('1/1/2012', periods=5, freq='M')

In [ ]:
ts = pd.Series(np.random.randn(len(rng)), index=rng)

In [ ]:
ts

In [ ]:
ps = ts.to_period()

In [ ]:
ps

In [ ]:
ps.to_timestamp()

Converting between period and timestamp enables some convenient arithmetic functions to be used. In the following example, we convert a quarterly frequency with year ending in November to 9am of the end of the month following the quarter end:

In [ ]:
prng = pd.period_range('1990Q1', '2000Q4', freq='Q-NOV')

In [ ]:
ts = pd.Series(np.random.randn(len(prng)), prng)

In [ ]:
ts.index = (prng.asfreq('M', 'e') + 1).asfreq('H', 's') + 9

In [ ]:
ts.head()

## Categoricals

Since version 0.15, pandas can include categorical data in a DataFrame. For full docs, see the [categorical introduction](http://pandas.pydata.org/pandas-docs/stable/categorical.html#categorical) and the [API documentation](http://pandas.pydata.org/pandas-docs/stable/api.html#api-categorical).

In [ ]:
df = pd.DataFrame({"id":[1,2,3,4,5,6], "raw_grade":['a', 'b', 'b', 'a', 'a', 'e']})

Convert the raw grades to a categorical data type.

In [ ]:
df["grade"] = df["raw_grade"].astype("category")

In [ ]:
df["grade"]

Rename the categories to more meaningful names (assigning to Series.cat.categories is inplace!)

In [ ]:
df["grade"].cat.categories = ["very good", "good", "very bad"]

Reorder the categories and simultaneously add the missing categories (methods under Series .cat return a new Series per default).

In [ ]:
df["grade"] = df["grade"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])

In [ ]:
df["grade"]

Sorting is per order in the categories, not lexical order.

In [ ]:
df.sort_values(by="grade")

Grouping by a categorical column shows also empty categories.

In [ ]:
df.groupby("grade").size()

## Plotting
[Plotting](http://pandas.pydata.org/pandas-docs/stable/visualization.html#visualization) docs.

In [ ]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))

In [ ]:
ts = ts.cumsum()

In [ ]:
ts.plot()

On DataFrame, plot() is a convenience to plot all of the columns with labels:

In [ ]:
df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index,
                  columns=['A', 'B', 'C', 'D'])

In [ ]:
df = df.cumsum()

In [ ]:
plt.figure(); df.plot(); plt.legend(loc='best')

## Getting Data In/Out

### CSV
[Writing to a csv file](http://pandas.pydata.org/pandas-docs/stable/io.html#io-store-in-csv)

In [ ]:
df.to_csv('foo.csv')

[Reading from a csv file](http://pandas.pydata.org/pandas-docs/stable/io.html#io-read-csv-table)

In [ ]:
pd.read_csv('foo.csv')

### HDF5
Reading and writing to [HDFStores](http://pandas.pydata.org/pandas-docs/stable/io.html#io-hdf5)

Writing to a HDF5 Store

In [ ]:
df.to_hdf('foo.h5','df')

Reading from a HDF5 Store

In [ ]:
pd.read_hdf('foo.h5','df')

### Excel

Reading and writing to [MS Excel](http://pandas.pydata.org/pandas-docs/stable/io.html#io-excel)

Writing to an excel file

In [ ]:
df.to_excel('foo.xlsx', sheet_name='Sheet1')

Reading from an excel file

In [ ]:
pd.read_excel('foo.xlsx', 'Sheet1', index_col=None, na_values=['NA'])

### Gotchas
If you are trying an operation and you see an exception like:

In [ ]:
if pd.Series([False, True, False]):
    print("I was true")

See [Comparisons](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-compare) for an explanation and what to do.

See [Gotchas](http://pandas.pydata.org/pandas-docs/stable/gotchas.html#gotchas) as well.