### Создание данных

Создадим массив 2d массив данных, который можно будет использовать. 

In [1]:
import pandas as pd
import numpy as np

sclaes = np.linspace(1, 50, 2)
means = np.linspace(1, 50, 1)

randoms  = np.array([np.random.normal(loc, scale, 10) for scale in sclaes for loc in means])
sclaes.shape, means.shape, sclaes, means
sclaes

array([ 1., 50.])

Посмотрим на созданный массив.

In [2]:
randoms

array([[  1.39597579,   0.40955465,   2.08813804,   2.28168591,
          0.44400308,   2.22246868,   1.44392936,   0.38369463,
          0.09427339,   1.99600282],
       [ 71.28574951,  39.10879652,  -2.2824845 ,  58.55637786,
         76.91242142, -42.39449432, -18.21763475, -53.28036501,
         40.43752237,  13.63603224]])

Посмотрим на статистики данных массивов


In [3]:
for i in randoms:
    print(np.mean(i), np.std(i)) 

1.2759726343011266 0.8223993486390807
18.37619213371739 44.01476867803109


Добавим массивы в DataFrame.

In [4]:
randoms.T
data = pd.DataFrame(randoms.T)
data

0          1
0  1.395976  71.285750
1  0.409555  39.108797
2  2.088138  -2.282485
3  2.281686  58.556378
4  0.444003  76.912421
5  2.222469 -42.394494
6  1.443929 -18.217635
7  0.383695 -53.280365
8  0.094273  40.437522
9  1.996003  13.636032

Создадим объект, который можно будет использовать для трансформации данных.

In [5]:
from sklearn.preprocessing import StandardScaler

scaller = StandardScaler()
scaller.fit(data)

StandardScaler()

Преобразуем данные

In [6]:
scalleddata = scaller.transform(data)

In [7]:
scalleddata

array([[ 0.14591835,  1.20208646],
       [-1.05352465,  0.47103745],
       [ 0.98755599, -0.46935784],
       [ 1.22290135,  0.91287963],
       [-1.01163693,  1.32992246],
       [ 1.15089591, -1.38068853],
       [ 0.20422769, -0.83139882],
       [-1.08496925, -1.62801167],
       [-1.43689224,  0.50122563],
       [ 0.87552378, -0.10769476]])

Посмотрим на статистики, которые были получыены STandardScaler()

In [8]:
scaller.mean_, scaller.scale_

(array([ 1.27597263, 18.37619213]), array([ 0.82239935, 44.01476868]))