Обратное преобразование. Декодирование

In [13]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# list_subs = ['AG', 'AT', 'GA', 'AA']
list_subs = ['T', 'A', 'G', 'G']
list_subs_vec = list(map(lambda x: list(tuple(x)), list_subs))

list_subs_np = np.array(list_subs).reshape(-1, 1)

list_subs_np

array([['T'],
       ['A'],
       ['G'],
       ['G']], dtype='<U1')

In [14]:
oh_enc = OneHotEncoder()
X_oh = oh_enc.fit_transform(list_subs_np)
print(X_oh)
# Если перевести в array, то получится похожее на закодированный векторы one-hot
X_oh.toarray()

  (0, 2)	1.0
  (1, 0)	1.0
  (2, 1)	1.0
  (3, 1)	1.0


array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [15]:
oh_enc.inverse_transform(X_oh)

array([['T'],
       ['A'],
       ['G'],
       ['G']], dtype='<U1')

In [8]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot']
data_vec = array(data).reshape(-1 , 1)
values = array(data)
print(values)

# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(-1, 1)
onehot_encoded = onehot_encoder.fit_transform(data_vec)
print(onehot_encoded)

# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)
data_vec

['cold' 'cold' 'warm' 'cold' 'hot']
[0 0 2 0 1]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
['cold']


array([['cold'],
       ['cold'],
       ['warm'],
       ['cold'],
       ['hot']], dtype='<U4')